---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rstapDP)
library(tidyverse)
library(coda)
theme_set(theme_bw())
```

```{r}
data("ClusterScales_one")

fit <- fdp_staplm(y = ClusterScales_one$BMI,
                  Z = cbind(1,matrix(ClusterScales_one$sex,ncol=1)),
                  X = matrix(ClusterScales_one$dists,ncol=1),
                  tau_0 = 1,
                  alpha_a = 1, 
                  alpha_b = 1,
                  K = 5,
                  iter_max = 5E4,
                  burn_in = 4.5E4,
                  thin = 1,
                  seed = 43431)
```
 
 
```{r}
plot_pairs(fit)
```


```{r}
plot(fit$beta)
```



```{r}
data("ClusterScales_two")

fit <- fdp_staplm(y = ClusterScales_two$BMI,
                  Z = cbind(1,ClusterScales_two$sex),
                  X = ClusterScales_two$dists_mat,
                  tau_0 = rep(1,ncol(ClusterScales_two$dists_mat)),
                  alpha_a = 1, 
                  alpha_b = 1,
                  K = 5,
                  iter_max = 1E4,
                  burn_in = 9E3,
                  thin = 1,
                  seed = 43431)
```



```{r}
plot_pairs(fit)
```


```{r}
plot_cluster_effects(fit)
```


```{r}
fit <- fdp_stapplm(y = ClusterScales_two$BMI,
                   Z = cbind(1,ClusterScales_two$sex),
                   X = ClusterScales_two$dists_mat,
                   nu_0 = 1,
                   alpha_a = 1, 
                   alpha_b = 1,
                   K = 5,
                   iter_max = 1E4,
                   burn_in = 9E3,
                   thin = 3,
                   seed = 43431)
```




```{r}
plot_pairs(fit)
```



```{r}
plot_cluster_effects(fit)
```



```{r}
data("Clusterdata_binomial")

fit <- fdp_stappglm(y = Clusterdata_binomial$y,
                   n = Clusterdata_binomial$n,
                   Z = cbind(1,Clusterdata_binomial$sex),
                   X = Clusterdata_binomial$dists,
                   nu_0 = 1,
                   alpha_a = 1, 
                   alpha_b = 1,
                   K = 5,
                   iter_max = 1,
                   burn_in = 0,
                   thin = 1,
                   seed = 43431)

```

