# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stapDP_backfit <- function(y, init_beta, X, iter_max, burn_in, thin, seed, num_posterior_samples) {
    .Call('_rstapDP_stapDP_backfit', PACKAGE = 'rstapDP', y, init_beta, X, iter_max, burn_in, thin, seed, num_posterior_samples)
}

