# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Penalized Functional Dirichlet Process Logistic Regression
#'
#' @param y a vector of continuous outcomes
#' @param Z a matrix of population level confounders
#' @param X a matrix of spatial temporal aggregated predictors
#' @param S penalty matrix for stap parameters
#' @param w a vector of weights for weighted regression
#' @param alpha_a alpha gamma prior shape hyperparameter
#' @param alpha_b alpha gamma prior scale hyperparameter
#' @param sigma_a precision gamma prior shape hyperparameter
#' @param sigma_b precision gamma prior scale hyperparameter
#' @param tau_a penalty gamma prior shape hyperparameter
#' @param tau_b penalty gamma prior scale hyperparameter
#' @param K truncation number
#' @param num_penalties number of penalty matrices accounted for in S
#' @param iter_max maximum number of iterations
#' @param burn_in number of burn in iterations
#' @param thin number by which to thin samples
#' @param seed rng initializer
#' @param num_posterior_samples total number of posterior samples
#' @param fix_alpha  boolean value that determines whether or not to fix alpha in sampler
stappDP_fit <- function(y, Z, X, S, w, alpha_a, alpha_b, sigma_a, sigma_b, tau_a, tau_b, K, num_penalties, iter_max, burn_in, thin, seed, num_posterior_samples, fix_alpha) {
    .Call(`_rstapDP_stappDP_fit`, y, Z, X, S, w, alpha_a, alpha_b, sigma_a, sigma_b, tau_a, tau_b, K, num_penalties, iter_max, burn_in, thin, seed, num_posterior_samples, fix_alpha)
}

